# action.yml
name: 'Vorpal Github Action With reviewdog'
description: 'Action Scan files with Vorpal engine and shows with reviewdog annotations and comments in PR'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
    default: ${{ github.token }}
  source_path:
    description: 'The path to the source code to scan'
    required: true
  folders_to_ignore:
    description: 'The paths of the folders to be ignored during the Vorpal scan'
    required: false
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is `github-pr-review`.
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is `added`.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
runs:
  using: 'docker'
  image: Dockerfile
  env:
    WORKSPACE_PATH: $GITHUB_WORKSPACE
branding:
  icon: 'monitor'
  color: 'purple'